tickets = [
{"description": "Алиса"},
{"description": "Чеширский Кот"},
{"description": "Винни-Пух"},
{"description": "Пятачок"},
{"description": "Ослик Иа"},
{"description": "Питер Пэн"},
{"description": "Карлсон"},
{"description": "Малыш"},
{"description": "Паддингтон"},
{"description": "Пеппи"},
{"description": "Муми-тролль"},
{"description": "Снусмумрик"},
{"description": "Буратино"},
{"description": "Мальвина"},
{"description": "Пьеро"},
{"description": "Артемон"},
{"description": "Дуремар"},
{"description": "Папа Карло"},
{"description": "Лиса Алиса"},
{"description": "Кот Базилио"},
{"description": "Карабас-Барабас"},
{"description": "Незнайка"},
{"description": "Винтик"},
{"description": "Шпунтик"},
{"description": "Пилюлькин"},
{"description": "Знайка"},
{"description": "Дядя Фёдор"},
{"description": "Печкин"},
{"description": "Кот Матроскин"},
{"description": "Иван-царевич"},
{"description": "Василиса Премудрая"},
{"description": "Дюймовочка"},
{"description": "Красная Шапочка"},
{"description": "Серый Волк"},
{"description": "Золушка"},
{"description": "Гном №7"},
{"description": "Гном №6"},
{"description": "Гном №5"},
{"description": "Гном №4"},
{"description": "Гном №3"},
{"description": "Гном №2"},
{"description": "Гном №1"},
{"description": "Спящая красавица"},
{"description": "Козлёнок №7"},
{"description": "Козлёнок №6"},
{"description": "Козлёнок №5"},
{"description": "Козлёнок №4"},
{"description": "Козлёнок №3"},
{"description": "Козлёнок №2"},
{"description": "Козлёнок №1"},
{"description": "Гарри Поттер"},
{"description": "Гермиона Грейнджер"},
{"description": "Рон Уизли"},
{"description": "Дамблдор"},
{"description": "Хагрид"},
{"description": "Маленький Принц"},
{"description": "Робин Гуд"},
{"description": "Емеля"},
{"description": "Астерикс"},
{"description": "Обеликс"},
{"description": "Тинтин"},
{"description": "Гулливер"},
{"description": "Жар-птица"},
{"description": "Белоснежка"},
{"description": "Баба-яга"},
{"description": "Колобок"},
{"description": "Мальчик-с-пальчик"},
{"description": "Русалочка"},
{"description": "Оле-Лукойе"},
{"description": "Репка"},
{"description": "Финдус"},
{"description": "Петсон"},
{"description": "Чиполлино"},
{"description": "Синьор Помидор"},
{"description": "Щелкунчик"},
{"description": "Мышка-норушка"},
{"description": "Мяули"},
{"description": "Царевна-лягушка"},
{"description": "Гадкий утёнок"},
{"description": "Бармалей"},
{"description": "Муха-Цокотуха"},
{"description": "Айболит"},
{"description": "Крокодил Гена"},
{"description": "Чебурашка"},
{"description": "Шалтай-Болтай"},
{"description": "Том Сойер"},
{"description": "Хоббит"},
{"description": "Тотошка"},
{"description": "Железный Дровосек"},
{"description": "Страшила"},
{"description": "Элли"},
{"description": "Илья Муромец"},
{"description": "Добрыня Никитич"},
{"description": "Леший"},
{"description": "Маугли"},
{"description": "Багира"},
{"description": "Медведь Балу"},
{"description": "Черепаха Тортила"},
{"description": "Груффало"},
{"description": "Умная собачка Соня"},
{"description": "Дениска Кораблёв"},
{"description": "Кай"},
{"description": "Герда"},
{"description": "Курочка Луиза"},
{"description": "Пиноккио"},
{"description": "Малыш Николя"},
{"description": "Барон Мюнхаузен"},
{"description": "Капитан Врунгель"},
{"description": "Братец Кролик"},
{"description": "Братец Лис"},
{"description": "Дядя Стёпа"},
{"description": "Ежик и Медвежонок"},
{"description": "Кот в сапогах"},
{"description": "Мэри Поппинс"},
{"description": "Нильс"},
{"description": "Робинзон Крузо"},
{"description": "Умка"},
{"description": "Старик Хоттабыч"},
{"description": "Чук"},
{"description": "Гек"},
{"description": "Эмиль из Леннеберги"},
{"description": "Домовёнок Кузя"},
{"description": "Нафаня"},
{"description": "Конёк-Горбунок"},
{"description": "Кот Учёный"},
{"description": "Царь Салтан"},
{"description": "Балда"},
{"description": "Золотая рыбка"},
{"description": "Царевна Лебедь"},
{"description": "Мойдодыр"},
{"description": "Водяной"},
{"description": "Змей Горыныч"},
{"description": "Карандаш и Самоделкин"},
{"description": "Зог"},
{"description": "Улитка"},
{"description": "Кит"},
{"description": "Любопытный Джордж"},
{"description": "Рапунцель"},
{"description": "Али-Баба"},
{"description": "Сорок разбойников"},
{"description": "Человеткин"},
{"description": "Курочка Ряба"},
{"description": "Морозко"},
{"description": "Месяц Апрель"},
{"description": "Карлхен"},
{"description": "Маленький Дед Мороз"},
{"description": "Барсукот"},
{"description": "Барсук Старший"},
{"description": "Котёнок Шмяк"},
{"description": "Тоня Глиммердал"},
{"description": "Простодурсен"},
{"description": "Оловянный солдатик"},
{"description": "Трилле"},
{"description": "Чарли"},
{"description": "Фрекен Бок"},
{"description": "Три поросёнка"},
{"description": "Оля и Яло"},
{"description": "Алиса Селезнёва"},
{"description": "Манюня"},
{"description": "Кролик Эдвард"},
{"description": "Витя Малеев"},
{"description": "Джельсомино"},
{"description": "Мио"},
{"description": "Юм-Юм"},
{"description": "Разбойник из Кардамона"},
{"description": "Серебряное Копытце"},
{"description": "Васёк Трубачёв"},
{"description": "Робин-Бобин"},
{"description": "Поллианна"},
{"description": "Электроник"},
{"description": "Снежная королева"},
{"description": "Дед-Надзор"},
{"description": "Рони - дочь разбойника"},
{"description": "Разбойник Хотценплотц"},
{"description": "Мишка Бруно"},
{"description": "Фокс Микки"},
{"description": "Маленький Мук"},
{"description": "Бобик"},
{"description": "Барбос"},
{"description": "Пёс по имени Мани"},
{"description": "Цветик-Семицветик"},
{"description": "Рыба-Кит"},
{"description": "Богатырь №1"},
{"description": "Богатырь №2"},
{"description": "Богатырь №3"},
{"description": "Богатырь №4"},
{"description": "Богатырь №5"},
{"description": "Богатырь №6"},
{"description": "Богатырь №7"},
{"description": "Мышонок Тео"},
{"description": "Неизвестный с хвостом"},
{"description": "Крошечка-Хаврошечка"},
{"description": "Бычок-смоляной бочок"},
{"description": "Гусь-Лебедь"},
{"description": "Хозяйка медной горы"},
{"description": "Сивка-Бурка"},
{"description": "Лисичка-сестричка"},
{"description": "Царевна Несмеяна"},
{"description": "Алладин"},
{"description": "Дядька Черномор"},
]